args: !!python/object:argparse.Namespace
  align_image_with_target_x: true
  batch_size: 32
  checkpoint_path: null
  gpus: 0
  latent_size: 128
  lr_step_epochs:
  - 32
  - 36
  - 68
  lr_values:
  - 0.001
  - 0.0001
  - 0.001
  - 0.0001
  mod_freeze_epoch: 36
  mod_steps:
  - 1
  - 5
  num_epochs: 72
  num_preds: 30
  reduce_dataset_size: 0
  test_split: /Users/xinyufang/Library/CloudStorage/Box-Box/Ferrari_SpA/crat-pred/dataset/argoverse/test_obs/data
  test_split_pre: /Users/xinyufang/Library/CloudStorage/Box-Box/Ferrari_SpA/crat-pred/dataset/argoverse/test_pre.pkl
  train_split: /Users/xinyufang/Library/CloudStorage/Box-Box/Ferrari_SpA/crat-pred/dataset/argoverse/train/data
  train_split_pre: /Users/xinyufang/Library/CloudStorage/Box-Box/Ferrari_SpA/crat-pred/dataset/argoverse/train_pre.pkl
  use_preprocessed: false
  val_batch_size: 32
  val_split: /Users/xinyufang/Library/CloudStorage/Box-Box/Ferrari_SpA/crat-pred/dataset/argoverse/val/data
  val_split_pre: /Users/xinyufang/Library/CloudStorage/Box-Box/Ferrari_SpA/crat-pred/dataset/argoverse/val_pre.pkl
  val_workers: 8
  wd: 0.01
  workers: 8
